# Generated by Django 5.2.1 on 2025-06-04 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_fix_doctor_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(help_text='Assigned medical professional', on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor'),
        ),
    ]
